-- LORDANTUNEZ Studio Supabase schema
-- Ejecuta este archivo en Supabase SQL Editor.

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    image text not null,
    tag text not null,
    title text not null,
    desc_short text not null,
    desc_long text not null,
    tags text[] not null default '{}',
    created_at timestamptz not null default now()
);

create table if not exists public.services (
    id bigint generated by default as identity primary key,
    icon text not null,
    title text not null,
    description text not null,
    tags text[] not null default '{}',
    color text not null default 'cyan',
    created_at timestamptz not null default now()
);

create table if not exists public.testimonials (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    photo text not null,
    text text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    sent_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.services enable row level security;
alter table public.testimonials enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Authenticated can manage projects" on public.projects;
drop policy if exists "Public can read services" on public.services;
drop policy if exists "Authenticated can manage services" on public.services;
drop policy if exists "Public can read testimonials" on public.testimonials;
drop policy if exists "Authenticated can manage testimonials" on public.testimonials;
drop policy if exists "Anyone can insert messages" on public.messages;
drop policy if exists "Authenticated can manage messages" on public.messages;

create policy "Public can read projects"
on public.projects for select
using (true);

create policy "Authenticated can manage projects"
on public.projects for all
to authenticated
using (true)
with check (true);

create policy "Public can read services"
on public.services for select
using (true);

create policy "Authenticated can manage services"
on public.services for all
to authenticated
using (true)
with check (true);

create policy "Public can read testimonials"
on public.testimonials for select
using (true);

create policy "Authenticated can manage testimonials"
on public.testimonials for all
to authenticated
using (true)
with check (true);

create policy "Anyone can insert messages"
on public.messages for insert
to anon, authenticated
with check (true);

create policy "Authenticated can manage messages"
on public.messages for all
to authenticated
using (true)
with check (true);

insert into public.projects (id, image, tag, title, desc_short, desc_long, tags) values
(1, 'https://images.unsplash.com/photo-1634942537034-2531766767d1?w=800&q=80', 'Branding', 'Aura Cosmetics', 'Identidad premium para marca de skincare', 'Diseñamos una identidad de marca premium para Aura Cosmetics, una startup de skincare sostenible. El proyecto incluyó naming, logotipo, sistema visual completo, packaging eco-friendly y dirección de arte para campañas digitales.', array['Logo Design','Brandbook','Packaging','Dirección de Arte']),
(2, 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80', 'UI/UX', 'TechFlow App', 'Diseño de app de productividad', 'Rediseño completo de la experiencia de usuario para TechFlow, una app de productividad con más de 2M de usuarios. Simplificamos flujos complejos y creamos un sistema de diseño escalable.', array['UX Research','UI Design','Design System','Prototipado']),
(3, 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&q=80', 'Packaging', 'Nómada Café', 'Packaging artesanal para café de especialidad', 'Creamos el packaging para Nómada Café, una tostadora artesanal de especialidad. Diseñamos bolsas con válvula de degasificación y etiquetas ilustradas a mano.', array['Packaging','Ilustración','Print Design','Mockups']),
(4, 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80', 'Publicidad', 'Velocity Motors', 'Campaña visual para concesionario premium', 'Campaña visual integral para el lanzamiento de la nueva gama de vehículos eléctricos de Velocity Motors. La campaña generó un aumento del 150% en consultas.', array['Campaña Digital','OOH','Social Media','Print']),
(5, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', 'Web Design', 'Finova Fintech', 'Sitio web para plataforma financiera', 'Diseño y desarrollo del sitio web corporativo para Finova. Creamos una experiencia web inmersiva que incrementó las solicitudes de demo en un 65%.', array['Web Design','Motion','UX Writing','Analytics']),
(6, 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80', 'Motion', 'Lumina Festival', 'Identidad visual y motion para festival de música', 'Identidad visual completa para Lumina, un festival de música electrónica y arte digital. Más de 5M de visualizaciones en redes sociales.', array['Motion Graphics','Branding','Social Content','Merch'])
on conflict (id) do nothing;

insert into public.services (id, icon, title, description, tags, color) values
(1, 'fas fa-fingerprint', 'Branding & Identidad', 'Desarrollamos identidades de marca completas: naming, logotipos, paletas cromáticas, tipografías y sistemas visuales coherentes que perduran en el tiempo.', array['Logo','Brandbook','Naming'], 'cyan'),
(2, 'fas fa-layer-group', 'Diseño UI/UX', 'Diseñamos interfaces digitales intuitivas y atractivas. Wireframes, prototipos interactivos y diseños de alta fidelidad para web y aplicaciones móviles.', array['Web','Apps','SaaS'], 'magenta'),
(3, 'fas fa-bullhorn', 'Diseño Publicitario', 'Campañas visuales de alto impacto: banners, flyers, brochures, vallas publicitarias y material promocional que captura la atención al instante.', array['Print','Digital','OOH'], 'yellow'),
(4, 'fas fa-hashtag', 'Redes Sociales', 'Estrategia visual para Instagram, TikTok, LinkedIn y más. Templates, carruseles, reels y contenido que genera engagement y comunidad.', array['Instagram','TikTok','LinkedIn'], 'cyan'),
(5, 'fas fa-play-circle', 'Motion Graphics', 'Animaciones 2D/3D, intros, transiciones y microinteracciones que dan vida a tu marca y comunican mensajes complejos de forma sencilla.', array['After Effects','Lottie','3D'], 'magenta'),
(6, 'fas fa-box-open', 'Packaging', 'Diseño de empaques que venden en el punto de venta. Etiquetas, cajas, bolsas y envases que comunican calidad y diferencian tu producto.', array['Etiquetas','Cajas','Mockups'], 'yellow')
on conflict (id) do nothing;

insert into public.testimonials (id, name, role, photo, text) values
(1, 'María González', 'CEO, Aura Cosmetics', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80', 'LORDANTUNEZ transformó completamente nuestra imagen de marca. El resultado superó todas nuestras expectativas. Profesionalismo, creatividad y atención al detalle en cada entrega.'),
(2, 'Carlos Mendoza', 'Founder, TechFlow', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80', 'Trabajar con el equipo de LORDANTUNEZ fue una experiencia excepcional. Entendieron nuestra visión desde el primer momento y la elevaron a un nivel que no imaginábamos posible.'),
(3, 'Laura Vargas', 'CMO, Finova', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80', 'El rediseño de nuestra app aumentó las conversiones en un 40%. El enfoque en UX fue clave. Sin duda, nuestro socio creativo de confianza para todos los proyectos futuros.')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.projects', 'id'), coalesce((select max(id) from public.projects), 1), true);
select setval(pg_get_serial_sequence('public.services', 'id'), coalesce((select max(id) from public.services), 1), true);
select setval(pg_get_serial_sequence('public.testimonials', 'id'), coalesce((select max(id) from public.testimonials), 1), true);
select setval(pg_get_serial_sequence('public.messages', 'id'), coalesce((select max(id) from public.messages), 1), true);
